# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alg_file_select.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Alogrithm_select(object):
    def setupUi(self, Alogrithm_select):
        Alogrithm_select.setObjectName("Alogrithm_select")
        Alogrithm_select.resize(537, 248)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Alogrithm_select)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.train_algorithm_url = QtWidgets.QLabel(Alogrithm_select)
        self.train_algorithm_url.setObjectName("train_algorithm_url")
        self.verticalLayout.addWidget(self.train_algorithm_url)
        self.train_alg_btn = QtWidgets.QPushButton(Alogrithm_select)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.train_alg_btn.setFont(font)
        self.train_alg_btn.setObjectName("train_alg_btn")
        self.verticalLayout.addWidget(self.train_alg_btn)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.test_algorithm_url = QtWidgets.QLabel(Alogrithm_select)
        self.test_algorithm_url.setObjectName("test_algorithm_url")
        self.verticalLayout_2.addWidget(self.test_algorithm_url)
        self.test_alg_btn = QtWidgets.QPushButton(Alogrithm_select)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.test_alg_btn.setFont(font)
        self.test_alg_btn.setObjectName("test_alg_btn")
        self.verticalLayout_2.addWidget(self.test_alg_btn)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Alogrithm_select)
        QtCore.QMetaObject.connectSlotsByName(Alogrithm_select)

    def retranslateUi(self, Alogrithm_select):
        _translate = QtCore.QCoreApplication.translate
        Alogrithm_select.setWindowTitle(_translate("Alogrithm_select", "算法选择"))
        self.train_algorithm_url.setText(_translate("Alogrithm_select", "未选择"))
        self.train_alg_btn.setText(_translate("Alogrithm_select", "训练算法"))
        self.test_algorithm_url.setText(_translate("Alogrithm_select", "未选择"))
        self.test_alg_btn.setText(_translate("Alogrithm_select", "测试算法"))
