# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AlogrithmForm(object):
    def setupUi(self, AlogrithmForm):
        AlogrithmForm.setObjectName("AlogrithmForm")
        AlogrithmForm.resize(1080, 720)
        self.verticalLayout = QtWidgets.QVBoxLayout(AlogrithmForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboCond = QtWidgets.QComboBox(AlogrithmForm)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.comboCond.setFont(font)
        self.comboCond.setObjectName("comboCond")
        self.horizontalLayout.addWidget(self.comboCond)
        self.lineValue = QtWidgets.QLineEdit(AlogrithmForm)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineValue.setFont(font)
        self.lineValue.setObjectName("lineValue")
        self.horizontalLayout.addWidget(self.lineValue)
        self.btnSelect = QtWidgets.QPushButton(AlogrithmForm)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnSelect.setFont(font)
        self.btnSelect.setObjectName("btnSelect")
        self.horizontalLayout.addWidget(self.btnSelect)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnAdd = QtWidgets.QPushButton(AlogrithmForm)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.btnAdd.setFont(font)
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayout.addWidget(self.btnAdd)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnDel = QtWidgets.QPushButton(AlogrithmForm)
        self.btnDel.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.btnDel.setFont(font)
        self.btnDel.setIconSize(QtCore.QSize(16, 16))
        self.btnDel.setObjectName("btnDel")
        self.horizontalLayout.addWidget(self.btnDel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton = QtWidgets.QPushButton(AlogrithmForm)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.horizontalLayout.setStretch(9, 5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout.setStretch(0, 1)

        self.pushButton1 = QtWidgets.QPushButton(AlogrithmForm)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.pushButton1.setFont(font)
        self.pushButton1.setObjectName("pushButton1")
        self.horizontalLayout.addWidget(self.pushButton1)

        self.retranslateUi(AlogrithmForm)
        QtCore.QMetaObject.connectSlotsByName(AlogrithmForm)

    def retranslateUi(self, AlogrithmForm):
        _translate = QtCore.QCoreApplication.translate
        AlogrithmForm.setWindowTitle(_translate("AlogrithmForm", "Form"))
        self.btnSelect.setText(_translate("AlogrithmForm", "查询"))
        self.btnAdd.setText(_translate("AlogrithmForm", "添加"))
        self.btnDel.setText(_translate("AlogrithmForm", "删除"))
        self.pushButton.setText(_translate("AlogrithmForm", "重置"))
        self.pushButton1.setText(_translate("AlogrithTemple", "算法模板"))
