# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClassifierForm(object):
    def setupUi(self, ClassifierForm):
        ClassifierForm.setObjectName("ClassifierForm")
        ClassifierForm.resize(1080, 720)
        self.verticalLayout = QtWidgets.QVBoxLayout(ClassifierForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboCond = QtWidgets.QComboBox(ClassifierForm)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.comboCond.setFont(font)
        self.comboCond.setObjectName("comboCond")
        self.horizontalLayout.addWidget(self.comboCond)
        self.lineValue = QtWidgets.QLineEdit(ClassifierForm)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineValue.setFont(font)
        self.lineValue.setObjectName("lineValue")
        self.horizontalLayout.addWidget(self.lineValue)
        self.btnSelect = QtWidgets.QPushButton(ClassifierForm)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnSelect.setFont(font)
        self.btnSelect.setObjectName("btnSelect")
        self.horizontalLayout.addWidget(self.btnSelect)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_import = QtWidgets.QPushButton(ClassifierForm)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.btn_import.setFont(font)
        self.btn_import.setObjectName("btn_import")
        self.horizontalLayout.addWidget(self.btn_import)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnDel = QtWidgets.QPushButton(ClassifierForm)
        self.btnDel.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.btnDel.setFont(font)
        self.btnDel.setIconSize(QtCore.QSize(16, 16))
        self.btnDel.setObjectName("btnDel")
        self.horizontalLayout.addWidget(self.btnDel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.horizontalLayout.setStretch(7, 5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        #self.tableWidget = QtWidgets.QTableWidget(ClassifierForm)
        #self.tableWidget.setObjectName("tableWidget")
        #self.tableWidget.setColumnCount(0)
        #self.tableWidget.setRowCount(0)
        #self.verticalLayout.addWidget(self.tableWidget)
        self.verticalLayout_2 = QtWidgets.QHBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        #spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 8)
        self.verticalLayout.setStretch(2, 1)

        self.retranslateUi(ClassifierForm)
        QtCore.QMetaObject.connectSlotsByName(ClassifierForm)

    def retranslateUi(self, ClassifierForm):
        _translate = QtCore.QCoreApplication.translate
        ClassifierForm.setWindowTitle(_translate("ClassifierForm", "Form"))
        self.btnSelect.setText(_translate("ClassifierForm", "查询"))
        self.btn_import.setText(_translate("ClassifierForm", "导入模型"))
        self.btnDel.setText(_translate("ClassifierForm", "删除"))
