# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_algorithmSelect.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_algorithmSelectForm(object):
    def setupUi(self, algorithm_table):
        algorithm_table.setObjectName("algorithm_table")
        algorithm_table.resize(1080, 640)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(algorithm_table.sizePolicy().hasHeightForWidth())
        algorithm_table.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(algorithm_table)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget_algorithm = QtWidgets.QTableWidget(algorithm_table)
        self.tableWidget_algorithm.setObjectName("tableWidget_algorithm")
        self.tableWidget_algorithm.setColumnCount(0)
        self.tableWidget_algorithm.setRowCount(0)


        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineValue = QtWidgets.QLineEdit(algorithm_table)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineValue.setFont(font)
        self.lineValue.setObjectName("lineValue1")
        self.horizontalLayout.addWidget(self.lineValue)
        self.btnSelect1 = QtWidgets.QPushButton(algorithm_table)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnSelect1.setFont(font)
        self.btnSelect1.setObjectName("btnSelect1")
        self.horizontalLayout.addWidget(self.btnSelect1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.tableWidget_algorithm)


        self.retranslateUi(algorithm_table)
        QtCore.QMetaObject.connectSlotsByName(algorithm_table)

    def retranslateUi(self, algorithm_table):
        _translate = QtCore.QCoreApplication.translate
        self.btnSelect1.setText(_translate("algorithm_table", "查询"))
        algorithm_table.setWindowTitle(_translate("algorithm_table", "Form"))
