from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_model_uploadForm(object):
    def setupUi(self, model_upload):
        model_upload.setObjectName("model_upload")
        model_upload.setFixedSize(600, 400)#窗口大小
        # model_import.resize(720, 673)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(model_upload.sizePolicy().hasHeightForWidth())
        model_upload.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(model_upload)
        self.verticalLayout.setObjectName("verticalLayout")
        # self.widget = QtWidgets.QWidget(model_import)
        font = QtGui.QFont()
        font.setPointSize(16)
        # .setFont(font)
        # .setObjectName("widget")
        self.label_Parameter_setting_title = QtWidgets.QLabel()
        self.label_Parameter_setting_title.setGeometry(QtCore.QRect(0, 20, 691, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_Parameter_setting_title.setFont(font)
        self.label_Parameter_setting_title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_Parameter_setting_title.setObjectName("label_Parameter_setting_title")
        horizon_layout_1 = QtWidgets.QHBoxLayout()
        horizon_layout_1.addWidget(self.label_Parameter_setting_title)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_upload = QtWidgets.QPushButton()
        self.pushButton_upload.setGeometry(QtCore.QRect(270, 580, 101, 31))
        self.pushButton_upload.setObjectName("pushButton_upload")
        self.pushButton_upload.setFixedSize(QtCore.QSize(151, 51))
        self.pushButton_upload.setFont(font)
        spacerItem_9_1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        spacerItem_9_2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)

        horizon_layout_9 = QtWidgets.QHBoxLayout()
        horizon_layout_9.addItem(spacerItem_9_1)
        horizon_layout_9.addWidget(self.pushButton_upload)
        horizon_layout_9.addItem(spacerItem_9_2)

        font = QtGui.QFont()
        font.setPointSize(16)
        self.label = QtWidgets.QLabel()
        self.label.setGeometry(QtCore.QRect(0, 70, 111, 41))
        self.label.setObjectName("label")
        self.label.setFont(font)
        self.Qcombox1=QtWidgets.QComboBox()
        self.Qcombox1.addItem('状态')
        self.Qcombox1.addItem('波形')
        self.Qcombox1.setFixedSize(225, 30)
        self.Qcombox1.move(50,130)
        horizon_layout_2 = QtWidgets.QHBoxLayout()
        horizon_layout_2.addWidget(self.label)
        horizon_layout_2.addWidget(self.Qcombox1)
        spacerItem_2 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        horizon_layout_2.addItem(spacerItem_2)
        horizon_layout_2.setStretch(-1, 1)



        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_model_select = QtWidgets.QPushButton()
        self.pushButton_model_select.setGeometry(QtCore.QRect(0, 410, 191, 51))
        self.pushButton_model_select.setObjectName("pushButton_model_select")
        self.pushButton_model_select.setFont(font)
        self.label_model_path = QtWidgets.QLabel()
        self.label_model_path.setGeometry(QtCore.QRect(190, 410, 441, 61))
        self.label_model_path.setFont(font)
        self.label_model_path.setObjectName("label_model_path")
        horizon_layout_7 = QtWidgets.QHBoxLayout()
        horizon_layout_7.addWidget(self.pushButton_model_select)
        horizon_layout_7.addWidget(self.label_model_path)

        #样本长度
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2 = QtWidgets.QLabel()
        self.label_2.setGeometry(QtCore.QRect(0, 130, 181, 41))
        self.label_2.setObjectName("label_2")
        self.label_2.setFont(font)
        self.lineEdit_epoch_length_name = QtWidgets.QLineEdit()
        self.lineEdit_epoch_length_name.setGeometry(QtCore.QRect(180, 130, 221, 41))
        self.lineEdit_epoch_length_name.setText("")
        self.lineEdit_epoch_length_name.setObjectName("lineEdit_epoch_length_name")
        self.lineEdit_epoch_length_name.setFont(font)
        int_validator = QtGui.QIntValidator()
        self.lineEdit_epoch_length_name.setValidator(int_validator)
        spacerItem_3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        horizon_layout_3 = QtWidgets.QHBoxLayout()
        horizon_layout_3.addWidget(self.label_2)
        horizon_layout_3.addWidget(self.lineEdit_epoch_length_name)
        horizon_layout_3.addItem(spacerItem_3)
        horizon_layout_3.setStretch(-1, 1)

        #分类数目
        font = QtGui.QFont()
        font.setPointSize(16)
        self.clslabel_3 = QtWidgets.QLabel()
        self.clslabel_3.setGeometry(QtCore.QRect(0, 130, 181, 41))
        self.clslabel_3.setObjectName("label_3")
        self.clslabel_3.setFont(font)
        self.lineEdit_clsnum = QtWidgets.QLineEdit()
        self.lineEdit_clsnum.setGeometry(QtCore.QRect(180, 130, 221, 41))
        self.lineEdit_clsnum.setText("")
        self.lineEdit_clsnum.setObjectName("lineEdit_epoch_length_name")
        self.lineEdit_clsnum.setFont(font)
        int_validator = QtGui.QIntValidator()
        self.lineEdit_clsnum.setValidator(int_validator)
        spacerItem_4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        horizon_layout_4 = QtWidgets.QHBoxLayout()
        horizon_layout_4.addWidget(self.clslabel_3)
        horizon_layout_4.addWidget(self.lineEdit_clsnum)
        horizon_layout_4.addItem(spacerItem_4)
        horizon_layout_4.setStretch(-1, 1)

        self.verticalLayout.addLayout(horizon_layout_1)
        self.verticalLayout.addLayout(horizon_layout_2)
        self.verticalLayout.addLayout(horizon_layout_3)
        self.verticalLayout.addLayout(horizon_layout_4)
        self.verticalLayout.addLayout(horizon_layout_7)
        self.verticalLayout.addLayout(horizon_layout_9)

        self.retranslateUi(model_upload)
        QtCore.QMetaObject.connectSlotsByName(model_upload)

    def retranslateUi(self, model_import):
        _translate = QtCore.QCoreApplication.translate
        model_import.setWindowTitle(_translate("model_upload", "模型上传"))
        self.label_Parameter_setting_title.setText(
            _translate("model_upload", "<html><head/><body><p align=\"center\">模型上传</p></body></html>"))
        self.pushButton_upload.setText(_translate("model_upload", "上传"))
        self.label.setText(_translate("model_import", "模型类型："))
        self.pushButton_model_select.setText(_translate("model_upload", "模型文件选择"))
        self.label_model_path.setText(_translate("model_upload",
                                                 "<html><head/><body><p><span style=\" font-size:12pt;\">模型文件路径：未选择</span></p></body></html>"))
        self.label_2.setText(_translate("model_upload", "样本长度："))
        self.clslabel_3.setText(_translate("model_upload", "分类数目："))
