# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_classifier.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClassifierForm(object):
    def setupUi(self, ClassifierForm):
        style_sheet = """
                           QPushButton{
                               max-width: 30ex;
                               max-height: 12ex;
                           }    
                       """
        ClassifierForm.setObjectName("ClassifierForm")
        ClassifierForm.resize(1080, 720)
        self.verticalLayout = QtWidgets.QVBoxLayout(ClassifierForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        #1
        self.comboCond = QtWidgets.QComboBox(ClassifierForm)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.comboCond.setFont(font)
        self.comboCond.setObjectName("comboCond")
        self.horizontalLayout.addWidget(self.comboCond)
        #2 输入框
        self.lineValue = QtWidgets.QLineEdit(ClassifierForm)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineValue.setFont(font)
        self.lineValue.setObjectName("lineValue")
        self.horizontalLayout.addWidget(self.lineValue)
        #3 单选按钮
        self.built_btn = QtWidgets.QRadioButton(ClassifierForm)#built
        self.ready_btn = QtWidgets.QRadioButton(ClassifierForm)#ready
        self.uploaded_btn = QtWidgets.QRadioButton(ClassifierForm)#uploaded
        self.btngroup1=QtWidgets.QButtonGroup()
        self.btngroup1.addButton(self.built_btn)
        self.btngroup1.addButton(self.ready_btn)
        self.btngroup1.addButton(self.uploaded_btn)
        self.built_btn.setText("built")
        self.ready_btn.setText("ready")
        self.uploaded_btn.setText("uploaded")
        self.horizontalLayout.addWidget(self.built_btn)
        self.horizontalLayout.addWidget(self.ready_btn)
        self.horizontalLayout.addWidget(self.uploaded_btn)

        # 3
        self.btnSelect = QtWidgets.QPushButton(ClassifierForm)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnSelect.setFont(font)
        self.btnSelect.setObjectName("btnSelect")
        self.lineValue.setFixedWidth(200)
        self.horizontalLayout.addWidget(self.btnSelect)
        #4
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        #5
        self.btn_import = QtWidgets.QPushButton(ClassifierForm)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.btn_import.setFont(font)
        self.btn_import.setObjectName("btn_import")
        self.btn_import.setMaximumSize(QtCore.QSize(130, 40))
        # self.btn_import.setFixedSize(100,35)
        self.horizontalLayout.addWidget(self.btn_import)
        #6
        self.btn_upload = QtWidgets.QPushButton(ClassifierForm)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.btn_upload.setFont(font)
        self.btn_upload.setObjectName("btn_upload")
        self.btn_upload.setMaximumSize(QtCore.QSize(130, 40))
        self.horizontalLayout.addWidget(self.btn_upload)
        # self.btn_upload.setStyleSheet(style_sheet)
        #7
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        #8
        self.btnDel = QtWidgets.QPushButton(ClassifierForm)
        self.btnDel.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.btnDel.setFont(font)
        self.btnDel.setIconSize(QtCore.QSize(16, 16))
        self.btnDel.setObjectName("btnDel")
        self.horizontalLayout.addWidget(self.btnDel)
        #9
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.horizontalLayout.setStretch(8, 5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QHBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout.addLayout(self.verticalLayout_2)
        #self.verticalLayout.setStretch(0, 1)
        #self.verticalLayout.setStretch(1, 17)
        #self.verticalLayout.setStretch(2, 2)

        self.retranslateUi(ClassifierForm)
        QtCore.QMetaObject.connectSlotsByName(ClassifierForm)

    def retranslateUi(self, ClassifierForm):
        _translate = QtCore.QCoreApplication.translate
        ClassifierForm.setWindowTitle(_translate("ClassifierForm", "Form"))
        self.btnSelect.setText(_translate("ClassifierForm", "查询"))
        self.btn_import.setText(_translate("ClassifierForm", "导入计划"))
        self.btn_upload.setText(_translate("ClassifierForm", "模型上传"))
        self.btnDel.setText(_translate("ClassifierForm", "删除"))
