# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_labelSelect.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_labelSelectForm(object):
    def setupUi(self, label_select):
        label_select.setObjectName("label_select")
        label_select.resize(663, 611)
        self.verticalLayout = QtWidgets.QVBoxLayout(label_select)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(label_select)
        self.widget.setObjectName("widget")
        self.pushButton_save = QtWidgets.QPushButton(self.widget)
        self.pushButton_save.setGeometry(QtCore.QRect(280, 550, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setObjectName("pushButton_save")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(360, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.labelType_listWidget = QtWidgets.QListWidget(self.widget)
        self.labelType_listWidget.setGeometry(QtCore.QRect(40, 70, 256, 431))
        self.labelType_listWidget.setObjectName("labelType_listWidget")
        self.selected_listWidget = QtWidgets.QListWidget(self.widget)
        self.selected_listWidget.setGeometry(QtCore.QRect(350, 70, 256, 431))
        self.selected_listWidget.setObjectName("selected_listWidget")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(40, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(label_select)
        QtCore.QMetaObject.connectSlotsByName(label_select)

    def retranslateUi(self, label_select):
        _translate = QtCore.QCoreApplication.translate
        label_select.setWindowTitle(_translate("label_select", "Dialog"))
        self.pushButton_save.setText(_translate("label_select", "保存"))
        self.label_3.setText(_translate("label_select", "已选通道"))
        self.label_4.setText(_translate("label_select", "通道列表"))
