# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_labelSelect.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_labelSelectForm(object):
    def setupUi(self, label_select):
        label_select.setObjectName("label_select")
        label_select.resize(663, 611)

        # 主垂直布局
        self.verticalLayout = QtWidgets.QVBoxLayout(label_select)
        self.verticalLayout.setObjectName("verticalLayout")

        # 使用QWidget作为容器（不再需要固定尺寸）
        self.container = QtWidgets.QWidget(label_select)
        self.verticalLayout.addWidget(self.container)

        # 网格布局（替代固定坐标）
        self.gridLayout = QtWidgets.QGridLayout(self.container)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setSpacing(15)

        # 通道列表标签
        self.label_4 = QtWidgets.QLabel(self.container)
        self.label_4.setFont(QtGui.QFont("Arial", 12))
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)

        # 参考通道标签
        self.label_REF = QtWidgets.QLabel(self.container)
        self.label_REF.setFont(QtGui.QFont("Arial", 12))
        self.gridLayout.addWidget(self.label_REF, 0, 1, 1, 1)

        # 已选通道标签
        self.label_3 = QtWidgets.QLabel(self.container)
        self.label_3.setFont(QtGui.QFont("Arial", 12))
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)

        # 列表控件（设置大小策略）
        self.labelType_listWidget = QtWidgets.QListWidget()
        self.labelType_listWidget.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addWidget(self.labelType_listWidget, 1, 0, 1, 1)

        self.REF_listWidget = QtWidgets.QListWidget()
        self.REF_listWidget.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addWidget(self.REF_listWidget, 1, 1, 1, 1)

        self.selected_listWidget = QtWidgets.QListWidget()
        self.selected_listWidget.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addWidget(self.selected_listWidget, 1, 2, 1, 1)

        # 按钮布局（水平居中）
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.addStretch()

        self.pushButton_save = QtWidgets.QPushButton(self.container)
        self.pushButton_save.setFont(QtGui.QFont("Arial", 12))
        self.horizontalLayout.addWidget(self.pushButton_save)

        self.horizontalLayout.addStretch()
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 3)

        # 设置列宽比例
        self.gridLayout.setColumnStretch(0, 2)  # 通道列表
        self.gridLayout.setColumnStretch(1, 2)  # 参考通道
        self.gridLayout.setColumnStretch(2, 3)  # 已选通道

        self.retranslateUi(label_select)
        QtCore.QMetaObject.connectSlotsByName(label_select)

    def retranslateUi(self, label_select):
        _translate = QtCore.QCoreApplication.translate
        label_select.setWindowTitle(_translate("label_select", "通道选择"))
        self.pushButton_save.setText(_translate("label_select", "保存"))
        self.label_3.setText(_translate("label_select", "已选通道"))
        self.label_REF.setText(_translate("label_select", "参考通道"))
        self.label_4.setText(_translate("label_select", "通道列表"))