# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addTheme.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLabel


class Ui_addTheme(object):
    def setupUi(self, addTheme):
        addTheme.setObjectName("addTheme")
        addTheme.resize(700, 800)
        self.gridLayout = QtWidgets.QGridLayout(addTheme)
        self.gridLayout.setObjectName("gridLayout")

        # font = QtGui.QFont()
        # font.setFamily("Arial Black")
        # font.setPointSize(12)

        font = QtGui.QFont()
        # font.setFamily("Source Han Sans")
        font.setPointSize(12)

        self.gbSettings = QtWidgets.QGroupBox(addTheme)
        self.gbSettings.setObjectName("gbSettings")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.gbSettings)
        self.gbSettings.setFont(font)
        self.gridLayout_19.setObjectName("gridLayout_19")



        self.labelState = QtWidgets.QLabel(self.gbSettings)
        self.labelState.setObjectName("labelState")
        self.labelState.setFont(font)
        self.gridLayout_19.addWidget(self.labelState, 6, 0, 1, 1)


        self.labelDesc = QtWidgets.QLabel(self.gbSettings)
        self.labelDesc.setObjectName("labelDesc")
        self.labelDesc.setFont(font)
        self.gridLayout_19.addWidget(self.labelDesc, 8, 0, 1, 1)

        self.textEdit = QtWidgets.QTextEdit(self.gbSettings)
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setFont(font)
        self.gridLayout_19.addWidget(self.textEdit, 9, 0, 1, 3)


        self.labelConfig = QtWidgets.QLabel(self.gbSettings)
        self.labelConfig.setObjectName("labelConfig")
        self.labelConfig.setFont(font)
        self.gridLayout_19.addWidget(self.labelConfig, 3, 0, 1, 1)

        # self.comboBoxState = QtWidgets.QComboBox(self.gbSettings)
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(2)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.comboBoxState.sizePolicy().hasHeightForWidth())
        # self.comboBoxState.setSizePolicy(sizePolicy)
        # self.comboBoxState.setObjectName("comboBoxState")
        # self.comboBoxState.setFont(font)
        # self.gridLayout_19.addWidget(self.comboBoxState, 6, 1, 1, 2)

        # 标注主题的状态
        self.themeStateLabel = QLabel('creating')
        self.themeStateLabel.setObjectName("comboBoxState")
        self.themeStateLabel.setFont(font)
        self.gridLayout_19.addWidget(self.themeStateLabel, 6, 1, 1, 2)


        self.themeEdit = QtWidgets.QLineEdit(self.gbSettings)
        self.themeEdit.setObjectName("themeEdit")
        self.themeEdit.setFont(font)
        self.gridLayout_19.addWidget(self.themeEdit, 0, 1, 1, 2)

        self.comboConfigId = QtWidgets.QLabel('默认为当前配置值')
        # self.comboConfigId = QtWidgets.QComboBox(self.gbSettings)
        self.comboConfigId.setObjectName("comboConfigId")
        self.comboConfigId.setFont(font)
        self.gridLayout_19.addWidget(self.comboConfigId, 3, 1, 1, 2)


        self.themeName = QtWidgets.QLabel(self.gbSettings)
        self.themeName.setObjectName("themeName")
        self.themeName.setFont(font)
        self.gridLayout_19.addWidget(self.themeName, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.gbSettings, 0, 0, 1, 1)
        self.gridLayoutSave = QtWidgets.QGridLayout()
        self.gridLayoutSave.setObjectName("gridLayoutSave")
        self.btnExit = QtWidgets.QPushButton(addTheme)
        self.btnExit.setObjectName("btnExit")
        self.btnExit.setFont(font)
        self.gridLayoutSave.addWidget(self.btnExit, 0, 2, 1, 1)
        self.btnConfirm = QtWidgets.QPushButton(addTheme)
        self.btnConfirm.setObjectName("btnConfirm")
        self.btnConfirm.setFont(font)
        self.gridLayoutSave.addWidget(self.btnConfirm, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayoutSave.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayoutSave.addItem(spacerItem1, 0, 3, 1, 1)
        self.gridLayout.addLayout(self.gridLayoutSave, 1, 0, 1, 1)

        self.retranslateUi(addTheme)
        QtCore.QMetaObject.connectSlotsByName(addTheme)

    def retranslateUi(self, addTheme):
        _translate = QtCore.QCoreApplication.translate
        addTheme.setWindowTitle(_translate("addTheme", "添加界面"))
        self.gbSettings.setTitle(_translate("addTheme", "标注主题"))
        self.labelState.setText(_translate("addTheme", "主题状态："))
        self.labelDesc.setText(_translate("addTheme", "主题说明："))
        self.labelConfig.setText(_translate("addTheme", "频率设置："))
        self.themeName.setText(_translate("addTheme", "主题名称："))
        self.btnExit.setText(_translate("addTheme", "取消"))
        self.btnConfirm.setText(_translate("addTheme", "确认"))
