# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addTheme.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLabel


class Ui_themeInfo(object):
    def setupUi(self, themeInfo):
        themeInfo.setObjectName("themeInfo")
        themeInfo.resize(700, 800)
        self.gridLayout = QtWidgets.QGridLayout(themeInfo)
        self.gridLayout.setObjectName("gridLayout")

        # font = QtGui.QFont()
        # font.setFamily("Arial Black")
        # font.setPointSize(12)

        font = QtGui.QFont()
        # font.setFamily("Source Han Sans")
        font.setPointSize(12)

        self.gbSettings = QtWidgets.QGroupBox(themeInfo)
        self.gbSettings.setObjectName("gbSettings")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.gbSettings)
        self.gbSettings.setFont(font)
        self.gridLayout_19.setObjectName("gridLayout_19")

        self.themeName = QtWidgets.QLabel(self.gbSettings)
        self.themeName.setObjectName("themeName")
        self.themeName.setFont(font)
        self.gridLayout_19.addWidget(self.themeName, 0, 0, 1, 1)


        self.labelConfig = QtWidgets.QLabel(self.gbSettings)
        self.labelConfig.setObjectName("labelConfig")
        self.labelConfig.setFont(font)
        self.gridLayout_19.addWidget(self.labelConfig, 3, 0, 1, 1)



        self.labelState = QtWidgets.QLabel(self.gbSettings)
        self.labelState.setObjectName("labelState")
        self.labelState.setFont(font)
        self.gridLayout_19.addWidget(self.labelState, 6, 0, 1, 1)


        self.labelDesc = QtWidgets.QLabel(self.gbSettings)
        self.labelDesc.setObjectName("labelDesc")
        self.labelDesc.setFont(font)
        self.gridLayout_19.addWidget(self.labelDesc, 8, 0, 1, 1)

        self.textEdit = QtWidgets.QTextEdit(self.gbSettings)
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setFont(font)
        self.textEdit.setReadOnly(True)
        self.gridLayout_19.addWidget(self.textEdit, 9, 0, 1, 3)



        # 标注主题的状态
        self.themeStateLabel = QLabel('creating')
        self.themeStateLabel.setObjectName("comboBoxState")
        self.themeStateLabel.setFont(font)
        self.gridLayout_19.addWidget(self.themeStateLabel, 6, 1, 1, 2)


        # 标注主题名称
        self.themeEdit = QLabel('')
        self.themeEdit.setObjectName("themeEdit")
        self.themeEdit.setFont(font)
        self.gridLayout_19.addWidget(self.themeEdit, 0, 1, 1, 2)


        self.comboConfigId = QtWidgets.QLabel('默认为当前配置值')
        # self.comboConfigId = QtWidgets.QComboBox(self.gbSettings)
        self.comboConfigId.setObjectName("comboConfigId")
        self.comboConfigId.setFont(font)
        self.gridLayout_19.addWidget(self.comboConfigId, 3, 1, 1, 2)



        self.gridLayout.addWidget(self.gbSettings, 0, 0, 1, 1)


        self.retranslateUi(themeInfo)
        QtCore.QMetaObject.connectSlotsByName(themeInfo)

    def retranslateUi(self, themeInfo):
        _translate = QtCore.QCoreApplication.translate
        themeInfo.setWindowTitle(_translate("themeInfo", "主题详细信息界面"))
        self.gbSettings.setTitle(_translate("themeInfo", "标注主题信息"))
        self.labelState.setText(_translate("themeInfo", "主题状态："))
        self.labelDesc.setText(_translate("themeInfo", "主题说明："))
        self.labelConfig.setText(_translate("themeInfo", "频率设置："))
        self.themeName.setText(_translate("themeInfo", "主题名称："))
