# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'progressBar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_progressbar(object):
    def __init__(self, window_title):
        self.window_title = window_title
        self.pb = None
    def setupUi(self, progressbar):
        progressbar.setObjectName("processbar")
        progressbar.resize(470, 140)
        self.pb = progressbar

        # 使用垂直布局代替固定几何位置
        layout = QtWidgets.QVBoxLayout(progressbar)
        layout.setContentsMargins(20, 20, 20, 20)  # 设置边距

        # 进度条
        self.progressBar = QtWidgets.QProgressBar()
        font = QtGui.QFont()
        font.setPointSize(12)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        layout.addWidget(self.progressBar)

        # 信息标签 - 放在进度条下方
        self.info_text = QtWidgets.QLabel()
        self.info_text.setObjectName("info_text")
        layout.addWidget(self.info_text)

        # 添加弹性空间使按钮保持在底部
        layout.addStretch(1)

        # 停止按钮
        self.stop_pushButton = QtWidgets.QPushButton()
        self.stop_pushButton.setObjectName("stop_pushButton")
        layout.addWidget(self.stop_pushButton, 0, QtCore.Qt.AlignHCenter)  # 水平居中

        self.retranslateUi(progressbar)
        QtCore.QMetaObject.connectSlotsByName(progressbar)

    def retranslateUi(self, processbar):
        _translate = QtCore.QCoreApplication.translate
        processbar.setWindowTitle(_translate("processbar", self.window_title))
        self.stop_pushButton.setText(_translate("processbar", "取消"))

