# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scanning.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Scanning(object):
    def setupUi(self, Scanning):
        Scanning.setObjectName("Scanning")
        Scanning.resize(1156, 757)
        self.verticalLayout = QtWidgets.QVBoxLayout(Scanning)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MainTextEdit = QtWidgets.QPlainTextEdit(Scanning)
        self.MainTextEdit.setObjectName("MainTextEdit")
        self.horizontalLayout.addWidget(self.MainTextEdit)
        self.subTextEdit = QtWidgets.QPlainTextEdit(Scanning)
        self.subTextEdit.setObjectName("subTextEdit")
        self.horizontalLayout.addWidget(self.subTextEdit)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Scanning)
        QtCore.QMetaObject.connectSlotsByName(Scanning)

    def retranslateUi(self, Scanning):
        _translate = QtCore.QCoreApplication.translate
        Scanning.setWindowTitle(_translate("Scanning", "Form"))
