# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addform.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDateTime, QDate, Qt
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import QDesktopWidget, QPushButton, QLabel
from view.dataImport_form.QCombox_Extend import ExtendedComboBox


class Ui_AddForm(object):
    def setupUi(self, Setting):
        Setting.setObjectName("Setting")
        Setting.resize(700, 800)

        self.gridLayout = QtWidgets.QGridLayout(Setting)
        self.gridLayout.setObjectName("gridLayout")

        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)

        self.gbSettings = QtWidgets.QGroupBox(Setting)
        self.gbSettings.setObjectName("gbSettings")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.gbSettings)
        self.gbSettings.setFont(font)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.labelpdoctorInfo = QtWidgets.QLabel(self.gbSettings)
        self.labelpdoctorInfo.setObjectName("labelpdoctorInfo")
        self.labelpdoctorInfo.setFont(font)
        self.gridLayout_19.addWidget(self.labelpdoctorInfo, 9, 0, 1, 1)


        self.pdoctorBtn = QPushButton('选择开单研究员')
        # self.pdoctorBtn.setStyleSheet('border: none;color:blue')
        self.pdoctorBtn.setCursor(Qt.PointingHandCursor)
        self.gridLayout_19.addWidget(self.pdoctorBtn, 9, 1, 1, 2)


        self.patientBtn = QPushButton('选择被试')
        # self.patientBtn.setStyleSheet('border: none;color:blue')
        self.patientBtn.setCursor(Qt.PointingHandCursor)
        self.gridLayout_19.addWidget(self.patientBtn, 6, 1, 1, 2)




        # 检查日期选项
        self.dateEdit = QtWidgets.QDateTimeEdit(QDateTime.currentDateTime(), self.gbSettings)
        self.dateEdit.setDisplayFormat("yyyy-MM-dd")
        # 设置最小日期
        # self.dateEdit.setMinimumDate(QDate.currentDate().addDays(-365))
        # 设置最大日期
        self.dateEdit.setMaximumDate(QDate.currentDate().addDays(365))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit.setFont(font)
        self.gridLayout_19.addWidget(self.dateEdit, 8, 1, 1, 2)

        # self.combo_cdoctor = QtWidgets.QComboBox(self.gbSettings)
        self.label_cdoctor = QLabel()
        self.label_cdoctor.setFont(QFont('', 12))
        self.label_cdoctor.setStyleSheet("color: black;")
        self.label_cdoctor.setObjectName("label_cdoctor")
        self.gridLayout_19.addWidget(self.label_cdoctor, 11, 1, 1, 2)

        self.labelcdoctorInfo = QtWidgets.QLabel(self.gbSettings)
        self.labelcdoctorInfo.setObjectName("labelcdoctorInfo")
        self.labelcdoctorInfo.setFont(font)
        self.gridLayout_19.addWidget(self.labelcdoctorInfo, 11, 0, 1, 1)


        self.labelDateInfo = QtWidgets.QLabel(self.gbSettings)
        self.labelDateInfo.setObjectName("labelDateInfo")
        self.labelDateInfo.setFont(font)
        self.gridLayout_19.addWidget(self.labelDateInfo, 8, 0, 1, 1)


        self.labelMoveInfo = QtWidgets.QLabel(self.gbSettings)
        self.labelMoveInfo.setObjectName("labelMoveInfo")
        self.labelMoveInfo.setFont(font)
        self.gridLayout_19.addWidget(self.labelMoveInfo, 12, 0, 1, 1)


        self.labelpatientInfo = QtWidgets.QLabel(self.gbSettings)
        self.labelpatientInfo.setObjectName("labelpatientInfo")
        self.labelpatientInfo.setFont(font)
        self.gridLayout_19.addWidget(self.labelpatientInfo, 6, 0, 1, 1)


        self.check_num = QtWidgets.QLineEdit(self.gbSettings)
        self.check_num.setPlaceholderText("必填")
        self.check_num.setObjectName("check_num")
        self.check_num.setFont(font)
        self.gridLayout_19.addWidget(self.check_num, 0, 1, 1, 2)


        self.labelcheckNumInfo = QtWidgets.QLabel(self.gbSettings)
        self.labelcheckNumInfo.setObjectName("labelcheckNumInfo")
        self.labelcheckNumInfo.setFont(font)
        self.gridLayout_19.addWidget(self.labelcheckNumInfo, 0, 0, 1, 1)


        self.checkInfo = QtWidgets.QTextEdit(self.gbSettings)
        self.checkInfo.setObjectName("checkInfo")
        self.checkInfo.setFont(font)
        self.gridLayout_19.addWidget(self.checkInfo, 13, 0, 1, 3)
        self.gridLayout.addWidget(self.gbSettings, 0, 0, 1, 1)


        self.gridLayoutSave = QtWidgets.QGridLayout()
        self.gridLayoutSave.setObjectName("gridLayoutSave")
        self.btnConfirm = QtWidgets.QPushButton(Setting)
        self.btnConfirm.setObjectName("btnConfirm")
        self.btnConfirm.setFont(font)
        self.gridLayoutSave.addWidget(self.btnConfirm, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayoutSave.addItem(spacerItem, 0, 0, 1, 1)
        self.btnExit = QtWidgets.QPushButton(Setting)
        self.btnExit.setObjectName("btnExit")
        self.btnExit.setFont(font)
        self.gridLayoutSave.addWidget(self.btnExit, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayoutSave.addItem(spacerItem1, 0, 3, 1, 1)
        self.gridLayout.addLayout(self.gridLayoutSave, 1, 0, 1, 1)

        self.retranslateUi(Setting)
        QtCore.QMetaObject.connectSlotsByName(Setting)

    def retranslateUi(self, Setting):
        _translate = QtCore.QCoreApplication.translate
        Setting.setWindowTitle(_translate("Setting", "添加实验单"))
        self.gbSettings.setTitle(_translate("Setting", "脑电检查"))
        self.labelpdoctorInfo.setText(_translate("Setting", "开单研究员："))
        self.labelcdoctorInfo.setText(_translate("Setting", "上传研究员："))
        self.labelDateInfo.setText(_translate("Setting", "实验日期："))
        self.labelMoveInfo.setText(_translate("Setting", "实验描述："))
        self.labelpatientInfo.setText(_translate("Setting", "被试姓名："))
        self.labelcheckNumInfo.setText(_translate("Setting", "实验单号："))
        self.btnConfirm.setText(_translate("Setting", "确认"))
        self.btnExit.setText(_translate("Setting", "取消"))
