# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_change_one.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDateTime, QDate


class Ui_ResearchImportForm(object):
    def setupUi(self, ResearchImportForm):
        ResearchImportForm.setObjectName("ResearchImportForm")
        ResearchImportForm.resize(1023, 627)
        self.gridLayout_7 = QtWidgets.QGridLayout(ResearchImportForm)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox_3 = QtWidgets.QGroupBox(ResearchImportForm)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_3.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")

        self.gridLayout_3.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.groupBox_3)
        self.verticalLayout_2.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox_4 = QtWidgets.QGroupBox(ResearchImportForm)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        # self.horizontalLayout_7.addWidget(self.selectLabelTypeBtn)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout.setVerticalSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.check_num = QtWidgets.QLineEdit(self.groupBox_4)
        self.check_num.setPlaceholderText("必填")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_num.sizePolicy().hasHeightForWidth())
        self.check_num.setSizePolicy(sizePolicy)
        self.check_num.setObjectName("check_num")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.check_num)
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.patientBtn = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.patientBtn.sizePolicy().hasHeightForWidth())
        self.patientBtn.setSizePolicy(sizePolicy)
        self.patientBtn.setObjectName("patientBtn")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.patientBtn)
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.pdoctorBtn = QtWidgets.QPushButton(self.groupBox_4)
        self.pdoctorBtn.setObjectName("pdoctorBtn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pdoctorBtn)

        # 在label_6和label_cdoctor之间添加选定标注类型的按钮
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)

        # 创建一个水平布局来放置上传研究员标签和标注类型按钮
        self.horizontalLayout_label = QtWidgets.QHBoxLayout()
        self.horizontalLayout_label.setObjectName("horizontalLayout_label")

        # 添加上传研究员显示标签
        self.label_cdoctor = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_cdoctor.sizePolicy().hasHeightForWidth())
        self.label_cdoctor.setSizePolicy(sizePolicy)
        self.label_cdoctor.setObjectName("label_cdoctor")
        self.horizontalLayout_label.addWidget(self.label_cdoctor)

        # 添加选定标注类型按钮
        self.selectLabelTypeBtn = QtWidgets.QPushButton(self.groupBox_4)
        self.selectLabelTypeBtn.setObjectName("selectLabelTypeBtn")
        self.selectLabelTypeBtn.setText("选定标注类型")  # 设置按钮文本
        self.horizontalLayout_label.addWidget(self.selectLabelTypeBtn)

        # 将水平布局添加到表单布局中
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_label)

        # 第5行：添加“文件类型”标签
        self.label_filetype = QtWidgets.QLabel(self.groupBox_4)
        self.label_filetype.setText("文件类型：")
        self.label_filetype.setObjectName("label_filetype")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_filetype)

        # 第5行：添加“文件类型”单选按钮（EEG / sEEG）
        self.horizontalLayout_filetype = QtWidgets.QHBoxLayout()
        self.horizontalLayout_filetype.setObjectName("horizontalLayout_filetype")

        self.radioEEG = QtWidgets.QRadioButton("EEG", self.groupBox_4)
        self.radioEEG.setObjectName("radio_eeg")
        self.radioEEG.setChecked(True)  # 默认选择 EEG
        self.horizontalLayout_filetype.addWidget(self.radioEEG)

        self.radioSEEG = QtWidgets.QRadioButton("sEEG", self.groupBox_4)
        self.radioSEEG.setObjectName("radioradioEEG")
        self.horizontalLayout_filetype.addWidget(self.radioSEEG)

        # 添加按钮组以实现互斥选择
        self.filetype_group = QtWidgets.QButtonGroup(self.groupBox_4)
        self.filetype_group.setObjectName("filetype_group")
        self.filetype_group.addButton(self.radioEEG)
        self.filetype_group.addButton(self.radioSEEG)

        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_filetype)



        # 检查日期选项
        self.dateEdit = QtWidgets.QDateTimeEdit(QDateTime.currentDateTime(), self.groupBox_4)
        self.dateEdit.setDisplayFormat("yyyy-MM-dd")
        # 设置最小日期
        # self.dateEdit.setMinimumDate(QDate.currentDate().addDays(-365))
        # 设置最大日期
        self.dateEdit.setMaximumDate(QDate.currentDate().addDays(365))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit.setFont(font)
        # self.gridLayout_19.addWidget(self.dateEdit, 8, 1, 1, 2)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dateEdit)

        self.horizontalLayout_7.addLayout(self.formLayout)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_12.addWidget(self.label_2)
        self.checkInfo = QtWidgets.QTextEdit(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.checkInfo.setFont(font)
        self.checkInfo.setObjectName("checkInfo")
        self.verticalLayout_12.addWidget(self.checkInfo)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.btnConfirm = QtWidgets.QPushButton(self.groupBox_4)
        self.btnConfirm.setObjectName("btnConfirm")
        self.horizontalLayout_8.addWidget(self.btnConfirm)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.btnExit = QtWidgets.QPushButton(self.groupBox_4)
        self.btnExit.setObjectName("btnExit")
        self.horizontalLayout_8.addWidget(self.btnExit)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.verticalLayout_12.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5.addLayout(self.verticalLayout_12)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.setStretch(0, 5)
        self.horizontalLayout_6.setStretch(1, 5)
        self.verticalLayout_11.addWidget(self.groupBox_4)
        self.verticalLayout_2.addLayout(self.verticalLayout_11)
        self.verticalLayout_2.setStretch(0, 5)
        self.verticalLayout_2.setStretch(1, 5)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")

        self.groupBox = QtWidgets.QGroupBox(ResearchImportForm)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")

        # 替换 QTextEdit 为 QTableWidget
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidget_1 = QtWidgets.QTableWidget(self.groupBox)  # 创建 QTableWidget
        self.tableWidget_1.setObjectName("tableWidget_1")
        self.tableWidget_1.setColumnCount(0)  # 根据需要设置列数
        self.tableWidget_1.setRowCount(0)  # 根据需要设置行数

        # 将 QTableWidget 添加到布局中
        self.gridLayout_2.addWidget(self.tableWidget_1, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.verticalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        # 添加布局中的间隔项
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)

        self.verticalLayout_4.setStretch(0, 5)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")

        self.groupBox_2 = QtWidgets.QGroupBox(ResearchImportForm)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget_2, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)

        # 创建两个按钮
        self.startUploadButton = QtWidgets.QPushButton(ResearchImportForm)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.startUploadButton.setFont(font)
        self.startUploadButton.setObjectName("startUploadButton")
        self.startUploadButton.setText("启动上传")  # 设置按钮的文本

        self.exitUploadButton = QtWidgets.QPushButton(ResearchImportForm)
        self.exitUploadButton.setFont(font)
        self.exitUploadButton.setObjectName("exitUploadButton")
        self.exitUploadButton.setText("返回")  # 设置按钮的文本

        # 将两个按钮添加到水平布局
        self.horizontalLayout_3.addWidget(self.startUploadButton)
        self.horizontalLayout_3.addWidget(self.exitUploadButton)

        # 将布局添加到verticalLayout_6
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_6)

        # 设置stretch
        self.verticalLayout_3.setStretch(0, 5)
        self.verticalLayout_3.setStretch(1, 1)

        # 最后将整个布局添加到verticalLayout
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 4)
        self.horizontalLayout.setStretch(1, 2)

        # 添加到gridLayout
        self.gridLayout_7.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(ResearchImportForm)
        QtCore.QMetaObject.connectSlotsByName(ResearchImportForm)

    def retranslateUi(self, ResearchImportForm):
        _translate = QtCore.QCoreApplication.translate
        ResearchImportForm.setWindowTitle(_translate("ResearchImportForm", "Form"))
        self.groupBox_3.setTitle(_translate("ResearchImportForm", "实验信息"))
        # self.addButton.setText(_translate("ResearchImportForm", "添加"))
        # self.delButton.setText(_translate("ResearchImportForm", "删除"))
        self.groupBox_4.setTitle(_translate("ResearchImportForm", "实验添加表单"))
        self.label.setText(_translate("ResearchImportForm", "实验单号："))
        self.label_3.setText(_translate("ResearchImportForm", "被试姓名："))
        self.patientBtn.setText(_translate("ResearchImportForm", "选择被试"))
        self.label_4.setText(_translate("ResearchImportForm", "实验日期："))
        self.label_5.setText(_translate("ResearchImportForm", "开单研究员："))
        self.pdoctorBtn.setText(_translate("ResearchImportForm", "选择研究员"))
        self.label_6.setText(_translate("ResearchImportForm", "上传研究员："))
        self.selectLabelTypeBtn.setText(_translate("ResearchImportForm", "选定标注类型"))
        self.label_filetype.setText(_translate("ResearchImportForm", "文件类型："))
        self.label_cdoctor.setText(_translate("ResearchImportForm", "TextLabel"))
        self.label_2.setText(_translate("ResearchImportForm", "实验描述："))
        self.btnConfirm.setText(_translate("ResearchImportForm", "确认添加"))
        self.btnExit.setText(_translate("ResearchImportForm", "取消添加"))
        # self.groupBox.setTitle(_translate("ResearchImportForm", "信息窗口"))
        # 将信息窗口改为待上传文件
        self.groupBox.setTitle(_translate("ResearchImportForm", "待上传文件"))
        # self.chooseBtn.setText(_translate("ResearchImportForm", "选择文件"))
        # self.processButton.setText(_translate("ResearchImportForm", "上传文件"))
        self.groupBox_2.setTitle(_translate("ResearchImportForm", "远程文件"))

        self.startUploadButton.setText(_translate("ResearchImportForm","启动上传"))
        self.exitUploadButton.setText(_translate("ResearchImportForm", "返回"))
        # self.sendMsgButton.setText(_translate("ResearchImportForm", "完成"))



