# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QuestionForm(object):
    def setupUi(self, QuestionForm):
        QuestionForm.setObjectName("QuestionForm")
        QuestionForm.resize(393, 256)
        self.gridLayout = QtWidgets.QGridLayout(QuestionForm)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.btnOK = QtWidgets.QPushButton(QuestionForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOK.sizePolicy().hasHeightForWidth())
        self.btnOK.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.btnOK.setFont(font)
        self.btnOK.setObjectName("btnOK")
        self.gridLayout.addWidget(self.btnOK, 0, 1, 1, 1)
        self.btnCancel = QtWidgets.QPushButton(QuestionForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCancel.sizePolicy().hasHeightForWidth())
        self.btnCancel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.btnCancel.setFont(font)
        self.btnCancel.setObjectName("btnCancel")
        self.gridLayout.addWidget(self.btnCancel, 0, 2, 1, 1)
        self.btnalgselect = QtWidgets.QPushButton(QuestionForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnalgselect.sizePolicy().hasHeightForWidth())
        self.btnalgselect.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.btnalgselect.setFont(font)
        self.btnalgselect.setObjectName("btnalgselect")
        self.gridLayout.addWidget(self.btnalgselect, 0, 0, 1, 1)

        self.retranslateUi(QuestionForm)
        QtCore.QMetaObject.connectSlotsByName(QuestionForm)

    def retranslateUi(self, QuestionForm):
        _translate = QtCore.QCoreApplication.translate
        QuestionForm.setWindowTitle(_translate("QuestionForm", "Form"))
        self.btnOK.setText(_translate("QuestionForm", "确定"))
        self.btnCancel.setText(_translate("QuestionForm", "取消"))
        self.btnalgselect.setText(_translate("QuestionForm", "算法选择"))
