from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QRegExp
from PyQt5.QtGui import QRegExpValidator, QIntValidator
from PyQt5.QtWidgets import QPushButton, QFrame, QSizePolicy


class Ui_EEGView(object):
    def setupUi(self, Ui_Form):
        Ui_Form.setObjectName("Ui_Form")
        #ManualForm.resize(1080, 760)
        self.gridLayout_1 = QtWidgets.QGridLayout(Ui_Form)
        self.gridLayout_1.setObjectName("gridLayout_1")

        self.groupBox1 = QtWidgets.QGroupBox(Ui_Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.groupBox1.setFont(font)
        self.groupBox1.setTitle("")
        self.groupBox1.setObjectName("groupBox1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox1)
        self.gridLayout_2.setObjectName("gridLayout_2")

        self.scrollArea_1 = QtWidgets.QScrollArea(self.groupBox1)
        self.scrollArea_1.setWidgetResizable(True)
        self.scrollArea_1.setObjectName("scrollArea_1")
        self.scrollAreaWidgetContents_1 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_1.setGeometry(QtCore.QRect(0, 0, 780, 720))
        self.scrollAreaWidgetContents_1.setObjectName("scrollAreaWidgetContents_1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.glCanvas = QtWidgets.QGridLayout()
        self.glCanvas.setSpacing(0)
        self.glCanvas.setObjectName("glCanvas")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.glBtn = QtWidgets.QGridLayout(self.groupBox)
        self.glBtn.setObjectName("glBtn")
        self.btnBegin = QtWidgets.QPushButton(self.groupBox)
        self.btnBegin.setObjectName("btnBegin")
        self.glBtn.addWidget(self.btnBegin, 0, 0, 1, 2)
        self.btnDowning = QtWidgets.QPushButton(self.groupBox)
        self.btnDowning.setObjectName("btnDowning")
        self.glBtn.addWidget(self.btnDowning, 0, 2, 1, 2)
        self.btnDown = QtWidgets.QPushButton(self.groupBox)
        self.btnDown.setObjectName("btnDown")
        self.glBtn.addWidget(self.btnDown, 0, 4, 1, 2)
        self.btnUp = QtWidgets.QPushButton(self.groupBox)
        self.btnUp.setObjectName("btnUp")
        self.glBtn.addWidget(self.btnUp, 0, 6, 1, 2)
        self.btnUping = QtWidgets.QPushButton(self.groupBox)
        self.btnUping.setObjectName("btnUping")
        self.glBtn.addWidget(self.btnUping, 0, 8, 1, 2)
        self.btnEnd = QtWidgets.QPushButton(self.groupBox)
        self.btnEnd.setObjectName("btnEnd")
        self.glBtn.addWidget(self.btnEnd, 0, 10, 1, 2)

        vline1 = QFrame()
        vline1.setFrameShape(QFrame.VLine)
        vline1.setFrameShadow(QFrame.Sunken)
        self.glBtn.addWidget(vline1, 0, 12, 1, 1)

        self.editTimeText = QtWidgets.QLabel(self.groupBox)
        self.editTimeText.setObjectName("editTimeText")
        self.editTimeText.setAlignment(Qt.AlignCenter)
        self.glBtn.addWidget(self.editTimeText, 0, 13, 1, 1)

        self.editTime = QtWidgets.QLineEdit(self.groupBox)
        self.editTime.setObjectName("editTime")
        self.editTime.setValidator(QRegExpValidator(QRegExp(r"^([01]\d|2[0-3]):[0-5]\d:[0-5]\d$")))
        self.glBtn.addWidget(self.editTime, 0, 14, 1, 1)

        self.secondsSpanText = QtWidgets.QLabel(self.groupBox)
        self.secondsSpanText.setObjectName("secondsSpanText")
        self.secondsSpanText.setAlignment(Qt.AlignCenter)
        self.glBtn.addWidget(self.secondsSpanText, 0, 15, 1, 1)
        self.secondsSpan = QtWidgets.QComboBox(self.groupBox)
        self.secondsSpan.setObjectName("secondsSpan")
        self.secondsSpan.setEditable(True)
        self.secondsSpan.setValidator(QIntValidator())
        self.glBtn.addWidget(self.secondsSpan, 0, 16, 1, 1)

        self.editTime.setFixedWidth(self.secondsSpan.sizeHint().width())

        self.moveLengthText = QtWidgets.QLabel(self.groupBox)
        self.moveLengthText.setObjectName("moveLengthText")
        self.moveLengthText.setAlignment(Qt.AlignCenter)
        self.glBtn.addWidget(self.moveLengthText, 0, 17, 1, 1)
        self.moveLength = QtWidgets.QComboBox(self.groupBox)
        self.moveLength.setObjectName("moveLength")
        self.moveLength.setEditable(True)
        self.moveLength.setValidator(QIntValidator())
        self.glBtn.addWidget(self.moveLength, 0, 18, 1, 1)
        self.sensitivityText = QtWidgets.QLabel(self.groupBox)
        self.sensitivityText.setObjectName("sensitivityText")
        self.sensitivityText.setAlignment(Qt.AlignCenter)
        self.glBtn.addWidget(self.sensitivityText, 0, 19, 1, 1)
        self.sensitivity = QtWidgets.QComboBox(self.groupBox)
        self.sensitivity.setObjectName("sensitivity")
        self.sensitivity.setEditable(True)
        self.sensitivity.setValidator(QIntValidator())
        self.glBtn.addWidget(self.sensitivity, 0, 20, 1, 1)

        vline4 = QFrame()
        vline4.setFrameShape(QFrame.VLine)
        vline4.setFrameShadow(QFrame.Sunken)
        self.glBtn.addWidget(vline4, 0, 21, 1, 1)

        self.subtractAverage = QtWidgets.QRadioButton(self.groupBox)
        self.subtractAverage.setObjectName("subtractAverage")
        self.subtractAverage.setChecked(True)
        self.subtractAverage.setAutoExclusive(False)

        self.glBtn.addWidget(self.subtractAverage, 0, 22, 1, 1)

        self.secondsLine = QtWidgets.QRadioButton(self.groupBox)
        self.secondsLine.setObjectName("secondsLine")
        self.secondsLine.setChecked(True)
        self.secondsLine.setAutoExclusive(False)

        self.glBtn.addWidget(self.secondsLine, 0, 23, 1, 1)

        vline3 = QFrame()
        vline3.setFrameShape(QFrame.VLine)
        vline3.setFrameShadow(QFrame.Sunken)
        self.glBtn.addWidget(vline3, 0, 24, 1, 1)

        self.scenarioSelectionBtn = QtWidgets.QPushButton(self.groupBox)
        self.scenarioSelectionBtn.setObjectName("scenarioSelectionBtn")
        self.glBtn.addWidget(self.scenarioSelectionBtn, 0, 25, 1, 2)
        self.channelSelectionBtn = QtWidgets.QPushButton(self.groupBox)
        self.channelSelectionBtn.setObjectName("channelSelectionBtn")
        self.glBtn.addWidget(self.channelSelectionBtn, 0, 27, 1, 2)
        self.sampleSelectionBtn = QtWidgets.QPushButton(self.groupBox)
        self.sampleSelectionBtn.setObjectName("sampleSelectionBtn")
        self.glBtn.addWidget(self.sampleSelectionBtn, 0, 29, 1, 2)

        vline2 = QFrame()
        vline2.setFrameShape(QFrame.VLine)
        vline2.setFrameShadow(QFrame.Sunken)
        self.glBtn.addWidget(vline2, 0, 32, 1, 1)
        self.btnStateAnnotate = QtWidgets.QPushButton(self.groupBox)
        self.btnStateAnnotate.setObjectName("btnStateAnnotate")
        self.glBtn.addWidget(self.btnStateAnnotate, 0, 33, 1, 2)

        self.glCanvas.addWidget(self.groupBox, 1, 0, 1, 1)
        self.listView = QtWidgets.QListView(self.scrollAreaWidgetContents_1)
        self.listView.setObjectName("listView")
        self.glCanvas.addWidget(self.listView, 0, 0, 1, 1)
        self.gridLayout_1.addWidget(self.groupBox1, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.scrollArea_1, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.glCanvas, 0, 0, 1, 1)
        self.scrollArea_1.setWidget(self.scrollAreaWidgetContents_1)

        self.groupBox2 = QtWidgets.QGroupBox(Ui_Form)
        self.groupBox2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox2.sizePolicy().hasHeightForWidth())
        self.groupBox2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.groupBox2.setFont(font)
        self.groupBox2.setTitle("")
        self.groupBox2.setObjectName("groupBox2")
        # self.groupBox2.setFixedWidth(400)
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gbPatientInfo = QtWidgets.QGroupBox(self.groupBox2)
        self.gbPatientInfo.setObjectName("gbPatientInfo")
        self.glPatientInfo = QtWidgets.QGridLayout(self.gbPatientInfo)
        self.glPatientInfo.setObjectName("glPatientInfo")
        self.labelPatientNameInfo = QtWidgets.QLabel(self.gbPatientInfo)
        self.labelPatientNameInfo.setObjectName("labelPatientNameInfo")
        self.glPatientInfo.addWidget(self.labelPatientNameInfo, 1, 0, 1, 1)
        self.labelPatientName = QtWidgets.QLabel(self.gbPatientInfo)
        self.labelPatientName.setObjectName("labelPatientName")
        self.glPatientInfo.addWidget(self.labelPatientName, 1, 1, 1, 1)
        self.labelPatientSexInfo = QtWidgets.QLabel(self.gbPatientInfo)
        self.labelPatientSexInfo.setObjectName("labelPatientSexInfo")
        self.glPatientInfo.addWidget(self.labelPatientSexInfo, 1, 2, 1, 1)
        self.labelPatientSex = QtWidgets.QLabel(self.gbPatientInfo)
        self.labelPatientSex.setObjectName("labelPatientSex")
        self.glPatientInfo.addWidget(self.labelPatientSex, 1, 3, 1, 1)
        self.labelPatientBirthInfo = QtWidgets.QLabel(self.gbPatientInfo)
        self.labelPatientBirthInfo.setObjectName("labelPatientBirthInfo")
        self.glPatientInfo.addWidget(self.labelPatientBirthInfo, 2, 0, 1, 1)
        self.labelPatientBirth = QtWidgets.QLabel(self.gbPatientInfo)
        self.labelPatientBirth.setObjectName("labelPatientBirth")
        self.glPatientInfo.addWidget(self.labelPatientBirth, 2, 1, 1, 2)
        self.labelPatientMeasureInfo = QtWidgets.QLabel(self.gbPatientInfo)
        self.labelPatientMeasureInfo.setObjectName("labelPatientMeasureInfo")
        self.glPatientInfo.addWidget(self.labelPatientMeasureInfo, 3, 0, 1, 1)
        self.labelPatientMeasure = QtWidgets.QLabel(self.gbPatientInfo)
        self.labelPatientMeasure.setObjectName("labelPatientMeasure")
        self.glPatientInfo.addWidget(self.labelPatientMeasure, 3, 1, 1, 2)

        self.gbSample = QtWidgets.QGroupBox(self.groupBox2)
        self.gbSample.setObjectName("gbSample")
        self.gridLayout_4.addWidget(self.gbSample, 1, 0, 1, 1)
        self.glSample = QtWidgets.QGridLayout(self.gbSample)
        self.glSample.setObjectName("glSample")

        self.hideWave = QtWidgets.QRadioButton(self.gbSample)
        self.hideWave.setObjectName("hideWave")

        self.hideWave.setChecked(True)
        self.hideWave.setAutoExclusive(False)
        self.glSample.addWidget(self.hideWave, 1, 0, 1, 1)


        self.hideState = QtWidgets.QRadioButton(self.gbSample)
        self.hideState.setObjectName("hideState")

        self.hideState.setChecked(True)
        self.hideState.setAutoExclusive(False)
        self.glSample.addWidget(self.hideState, 1, 1, 1, 1)

        self.labelMeasureTimeInfo = QtWidgets.QLabel(self.gbPatientInfo)
        self.labelMeasureTimeInfo.setObjectName("labelMeasureTimeInfo")
        self.glPatientInfo.addWidget(self.labelMeasureTimeInfo, 4, 0, 1, 1)
        self.labelMeasureTime = QtWidgets.QLabel(self.gbPatientInfo)
        self.labelMeasureTime.setObjectName("labelMeasureTime")
        self.glPatientInfo.addWidget(self.labelMeasureTime, 4, 1, 1, 2)

        self.labelFileNameInfo = QtWidgets.QLabel(self.gbPatientInfo)
        self.labelFileNameInfo.setObjectName("labelFileNameInfo")
        self.glPatientInfo.addWidget(self.labelFileNameInfo, 5, 0, 1, 1)
        self.labelFileName = QtWidgets.QLabel(self.gbPatientInfo)
        self.labelFileName.setObjectName("labelFileName")
        self.glPatientInfo.addWidget(self.labelFileName, 5, 1, 1, 2)


        self.gridLayout_4.addWidget(self.gbPatientInfo, 0, 0, 1, 1)

        self.tableWidget = QtWidgets.QTableWidget(self.groupBox2)
        self.tableWidget.setObjectName("tableWidget")
        self.gridLayout_4.addWidget(self.tableWidget, 2, 0, 1, 1)

        self.gbSampleInfo = QtWidgets.QGroupBox(self.groupBox2)
        self.gbSampleInfo.setObjectName("gbSampleInfo")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gbSampleInfo)
        self.gridLayout_5.setObjectName("gridLayout_2")

        self.labelTypeInfo = QtWidgets.QLabel(self.gbSampleInfo)
        self.labelTypeInfo.setObjectName("labelTypeInfo")
        self.gridLayout_5.addWidget(self.labelTypeInfo, 0, 0, 1, 1)
        self.labelType = QtWidgets.QLabel(self.gbSampleInfo)
        self.labelType.setObjectName("labelType")
        self.gridLayout_5.addWidget(self.labelType, 0, 1, 1, 2)

        self.labelChannelInfo = QtWidgets.QLabel(self.gbSampleInfo)
        self.labelChannelInfo.setObjectName("labelChannelInfo")
        self.gridLayout_5.addWidget(self.labelChannelInfo, 1, 0, 1, 1)
        self.labelChannel = QtWidgets.QLabel(self.gbSampleInfo)
        self.labelChannel.setObjectName("labelChannel")
        self.gridLayout_5.addWidget(self.labelChannel, 1, 1, 1, 2)

        self.labelLengthInfo = QtWidgets.QLabel(self.gbSampleInfo)
        self.labelLengthInfo.setObjectName("labelLengthInfo")
        self.gridLayout_5.addWidget(self.labelLengthInfo, 2, 0, 1, 1)
        self.labelLength = QtWidgets.QLabel(self.gbSampleInfo)
        self.labelLength.setObjectName("labelLength")
        self.gridLayout_5.addWidget(self.labelLength, 2, 1, 1, 2)

        self.labelBeginInfo = QtWidgets.QLabel(self.gbSampleInfo)
        self.labelBeginInfo.setObjectName("labelBeginInfo")
        self.gridLayout_5.addWidget(self.labelBeginInfo, 3, 0, 1, 1)
        self.labelBegin = QtWidgets.QLabel(self.gbSampleInfo)
        self.labelBegin.setObjectName("labelBegin")
        self.gridLayout_5.addWidget(self.labelBegin, 3, 1, 1, 2)

        self.labelEndInfo = QtWidgets.QLabel(self.gbSampleInfo)
        self.labelEndInfo.setObjectName("labelEndInfo")
        self.gridLayout_5.addWidget(self.labelEndInfo, 4, 0, 1, 1)
        self.labelEnd = QtWidgets.QLabel(self.gbSampleInfo)
        self.labelEnd.setObjectName("labelEnd")
        self.gridLayout_5.addWidget(self.labelEnd, 4, 1, 1, 2)

        self.labelAmpInfo = QtWidgets.QLabel(self.gbSampleInfo)
        self.labelAmpInfo.setObjectName("labelAmpInfo")
        self.gridLayout_5.addWidget(self.labelAmpInfo, 5, 0, 1, 1)
        self.labelAmp = QtWidgets.QLabel(self.gbSampleInfo)
        self.labelAmp.setObjectName("labelAmp")
        self.gridLayout_5.addWidget(self.labelAmp, 5, 1, 1, 2)

        self.gridLayout_4.addWidget(self.gbSampleInfo, 3, 0, 1, 1)

        self.returnBtn = QtWidgets.QPushButton(self.groupBox2)
        self.returnBtn.setObjectName("returnBtn")
        self.gridLayout_4.addWidget(self.returnBtn, 4, 0, 1, 1)

        self.gridLayout_1.addWidget(self.groupBox2, 0, 1, 1, 1)

        self.retranslateUi(Ui_Form)
        QtCore.QMetaObject.connectSlotsByName(Ui_Form)


    def retranslateUi(self, ManualForm):
        _translate = QtCore.QCoreApplication.translate
        self.returnBtn.setText(_translate("Return", "返回"))
        self.btnBegin.setText(_translate("Begin", "|<"))
        self.btnDowning.setText(_translate("Scroll Backward", "<<"))
        self.btnDown.setText(_translate("Backward", "<"))
        self.btnUp.setText(_translate("Forward", ">"))
        self.btnUping.setText(_translate("Scroll Forward", ">>"))
        self.btnEnd.setText(_translate("End", ">|"))
        self.editTimeText.setText(_translate("EditTime Text", " 窗口位置:"))
        self.editTime.setText("00:00:00")
        self.secondsLine.setText(_translate("Seconds Line", "秒线 "))
        self.subtractAverage.setText(_translate("Subtract Average", "减平均 "))
        self.sensitivityText.setText(_translate("Sensitivity Text", " 灵敏度(uV/mm): "))
        self.sensitivity.setCurrentText("10")
        self.secondsSpanText.setText(_translate("secondsSpan Text", " 秒跨度(mm/s): "))
        self.secondsSpan.setCurrentText("30")
        self.moveLengthText.setText(_translate("MoveLength Text", " 移动长度(s): "))
        self.scenarioSelectionBtn.setText(_translate("ScenarioSelection Btn", "参考方案"))
        self.channelSelectionBtn.setText(_translate("ChannelSelection", "导联选择"))
        self.sampleSelectionBtn.setText(_translate("SampleSelection Btn", "样本选择"))
        self.btnStateAnnotate.setText(_translate("Annotate State", "标注状态"))
        ManualForm.setWindowTitle(_translate("ManualForm", "Form44"))

        self.gbPatientInfo.setTitle(_translate("Patient Info", "病人信息"))
        self.labelPatientNameInfo.setText(_translate("Name: ", "姓名："))
        self.labelPatientName.setText(" ")
        self.labelPatientSexInfo.setText(_translate("Gender: ", "性别："))
        self.labelPatientSex.setText(" ")
        self.labelPatientBirthInfo.setText(_translate("Birthday: ", "出生日期："))
        self.labelPatientBirth.setText(" ")
        self.labelPatientMeasureInfo.setText(_translate("MeasureDay: ", "测量日期："))
        self.labelPatientMeasure.setText(" ")
        self.labelMeasureTimeInfo.setText(_translate("MeasureTime: ", "测量时间："))
        self.labelMeasureTime.setText(" ")
        self.labelFileNameInfo.setText(_translate("Filename: ", "文件名称："))
        self.labelFileName.setText(" ")


        self.gbSampleInfo.setTitle(_translate("Sample Info", "当前样本"))
        self.labelTypeInfo.setText(_translate("Type: ", "类型："))
        self.labelType.setText("")
        self.labelChannelInfo.setText(_translate("Channel: ", "导联："))
        self.labelChannel.setText("")
        self.labelLengthInfo.setText(_translate("Length(s): ", "时限(s)："))
        self.labelLength.setText("")
        self.labelBeginInfo.setText(_translate("Start: ", "开始："))
        self.labelBegin.setText("")
        self.labelEndInfo.setText(_translate("End: ", "结束："))
        self.labelEnd.setText("")
        self.labelAmpInfo.setText(_translate("Amplitude(uV): ", "波幅(µV)："))
        self.labelAmp.setText("")

        self.gbSample.setTitle(_translate("Sample", "样本操作"))
        self.hideWave.setText(_translate("hideWave", "波形 "))
        self.hideState.setText(_translate("hideState", "状态 "))