# -*- coding: utf-8 -*-
from functools import partial

# Form implementation generated from reading ui file '.\setBdf.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import QLabel, QScrollArea, QWidget, QVBoxLayout, QHBoxLayout, QGroupBox, QDialog


class Ui_Ref(QDialog):
    def setupUi(self,  Setting, dgroup,curRef):
        Setting.setObjectName("Setting")
        Setting.resize(1380, 766)


        self.dgroup=dgroup



        iFont = QFont("", 11)
        self.dgroupKeys=list(self.dgroup.keys())
        glen=len(self.dgroupKeys)
        self.lb_g=[]






        # 创建一个 QScrollArea
        self.scroll_area = QtWidgets.QScrollArea()
        self.scroll_area.setWidgetResizable(True)

        # 创建一个 QWidget 作为 QScrollArea 的内容
        self.scroll_area_content = QtWidgets.QWidget()
        self.scroll_area.setWidget(self.scroll_area_content)

        self.layout = QtWidgets.QHBoxLayout(Setting)
        Setting.setLayout(self.layout)
        self.main_layout_1 = QtWidgets.QVBoxLayout(self.scroll_area_content)
        self.layout.addWidget(self.scroll_area)
        #self.main_layout_1.addWidget(self.scroll_area)
        self.main_layout_2 = QtWidgets.QVBoxLayout()


        self.label_2 = QtWidgets.QLabel(Setting)
        # self.label_2.setGeometry(QtCore.QRect(10, 20, 54, 12))
        self.label_2.setObjectName("label_2")
        self.main_layout_1.addWidget(self.label_2)


        self.pb_ok = QtWidgets.QPushButton(Setting)
        # self.pb_ok.setGeometry(QtCore.QRect(1000, 700, 61, 23))
        self.pb_ok.setObjectName("pb_ok")

        self.pb_cancel = QtWidgets.QPushButton(Setting)
        # self.pb_cancel.setGeometry(QtCore.QRect(1500, 700, 61, 23))
        self.pb_cancel.setObjectName("pb_cancel")



        self.list_widget = QtWidgets.QListWidget()


        y=0
        index=0
        for i in range(glen):
            # self.lb_g.append(QtWidgets.QLabel(Setting))
            chs = self.dgroup.get(self.dgroupKeys[i])
            self.lb_g.append(QtWidgets.QRadioButton())
            # self.lb_g[i].setGeometry(QtCore.QRect(10, 60+y, 150, 20))
            self.lb_g[i].setObjectName(f"{self.dgroupKeys[i]}")
            self.lb_g[i].setText(f"{self.dgroupKeys[i]}")
            self.lb_g[i].clicked.connect(lambda checked, ch=chs: self.initChannels(ch))
            self.lb_g[i].setStyleSheet('height : 20px;width:60px;color:blue;text-align: left;')

            self.lb_g[i].setCursor(Qt.PointingHandCursor)
            if self.dgroupKeys[i]==curRef:
                self.lb_g[i].setChecked(True)
                self.initChannels(chs)

            # chs=self.dgroup.get(self.dgroupKeys[i])
            self.main_layout_1.addWidget(self.lb_g[i])
            self.main_layout_1.setAlignment(Qt.AlignTop)

        self.layout.addWidget(self.list_widget)

        self.main_layout_2.addStretch(1)
        self.main_layout_2.addWidget(self.pb_ok)
        self.main_layout_2.addWidget(self.pb_cancel)
        #self.main_layout_2.addStretch(1)

        self.layout.addLayout(self.main_layout_2)

        self.layout.setStretch(0,2)
        self.layout.setStretch(1, 3)
        self.layout.setStretch(2, 1)


        self.retranslateUi(Setting)
        QtCore.QMetaObject.connectSlotsByName(Setting)



    def retranslateUi(self, Setting):
        _translate = QtCore.QCoreApplication.translate
        Setting.setWindowTitle(_translate("Setting", "参考方案"))


        self.label_2.setText(_translate("Setting", "参考方案："))
        # self.radioButtonMontage_1.setText(_translate("Setting", "头皮脑电"))
        # self.radioButtonMontage_2.setText(_translate("Setting", "颅内脑电"))
        self.pb_ok.setText(_translate("Setting", "确定"))
        self.pb_cancel.setText(_translate("Setting", "取消"))

    def initChannels(self,chs):
        glen = len(self.dgroupKeys)
        index = 0
        self.list_widget.insertItem(1,"ok")
        # self.radioButtonMontage_1.setChecked(True)
        # self.radioButtonMontage_1.hide()
        # self.radioButtonMontage_2.hide()
        self.list_widget.clear()
        # for i in range(glen):
        #     self.lb_g[i].setText(f"{self.dgroupKeys[i]}")
        #     chs = self.dgroup.get(self.dgroupKeys[i])
        for j in range(len(chs)):
            #self.ck_g[index].setText(f"{chs[j]}")
            self.list_widget.insertItem(j, chs[j])
            # if chs[j] in self.dgroup_filter:
            #     self.ck_g[index].setChecked(True)
            # else:
            #     self.ck_g[index].setChecked(False)
            #index += 1
        #self.ck_g[index-1].show()
            #self.ck_g[index-1].setChecked(True)



