# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QHBoxLayout, QPushButton, QLabel, QLineEdit
from PyQt5.QtCore import QRect, Qt
from functools import partial


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1190, 822)
        self.verticalLayout_all = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_all.setObjectName("verticalLayout_all")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_left = QtWidgets.QVBoxLayout()
        self.verticalLayout_left.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_left.setObjectName("verticalLayout_left")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        spacerItem1 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)

        self.label3 = QtWidgets.QLabel(Form)
        self.label3.setAlignment(Qt.AlignRight | Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPixelSize(16)
        font.setFamily("Arial")
        self.label3.setFont(font)
        self.label3.setObjectName("label3")
        self.horizontalLayout.addWidget(self.label3)
        self.comboBox = QtWidgets.QComboBox(Form)

        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setMaximumSize(QtCore.QSize(300, 31))

        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)




        self.label2 = QtWidgets.QLabel(Form)
        self.label2.setObjectName("label2")

        self.label2.setFont(font)
        self.horizontalLayout.addWidget(self.label2)

        self.lineEditDate1 = QtWidgets.QLineEdit(Form)
        self.lineEditDate1.setEnabled(True)
        self.lineEditDate1.setObjectName("lineEditDate1")

        self.lineEditDate1.setFont(font)
        self.lineEditDate1.setMaximumSize(QtCore.QSize(120, 26))
        self.horizontalLayout.addWidget(self.lineEditDate1)

        self.date_lineEdit = QtWidgets.QDateTimeEdit(Form)
        self.date_lineEdit.setEnabled(True)

        self.date_lineEdit.setDisplayFormat("yyyy-MM-dd")
        self.date_lineEdit.setObjectName("date_lineEdit")
        self.date_lineEdit.setCalendarPopup(True)
        self.date_lineEdit.setMaximumSize(QtCore.QSize(18, 26))
        # self.date_lineEdit.setFixedSize(20, 30)
        self.date_lineEdit.dateChanged.connect(partial(self.dateChanged, 1))


        self.date_lineEdit.setFont(font)
        self.horizontalLayout.addWidget(self.date_lineEdit)

        self.label4 = QtWidgets.QLabel(Form)
        self.label4.setObjectName("label4")

        self.label4.setFont(font)
        self.horizontalLayout.addWidget(self.label4)

        self.lineEditDate2 = QtWidgets.QLineEdit(Form)
        self.lineEditDate2.setEnabled(True)
        self.lineEditDate2.setObjectName("lineEditDate2")

        self.lineEditDate2.setFont(font)
        self.lineEditDate2.setMaximumSize(QtCore.QSize(120, 26))
        self.horizontalLayout.addWidget(self.lineEditDate2)

        self.date_lineEdit2 = QtWidgets.QDateTimeEdit(Form)
        self.date_lineEdit2.setEnabled(True)

        self.date_lineEdit2.setDisplayFormat("yyyy-MM-dd")
        self.date_lineEdit2.setObjectName("date_lineEdit")
        self.date_lineEdit2.setCalendarPopup(True)
        self.date_lineEdit2.setMaximumSize(QtCore.QSize(18, 26))
        self.date_lineEdit2.dateChanged.connect(partial(self.dateChanged, 2))


        self.date_lineEdit2.setFont(font)
        self.horizontalLayout.addWidget(self.date_lineEdit2)


        self.historyListButton = QtWidgets.QPushButton(Form)
        self.historyListButton.setMinimumSize(QtCore.QSize(90, 0))
        self.historyListButton.setMaximumSize(QtCore.QSize(90, 16777215))

        # font.setBold(True)
        # font.setWeight(75)
        self.historyListButton.setFont(font)
        # self.historyListButton.setStyleSheet("background-color: rgb(255, 0, 0);\n"
        #                                      "color: rgb(255, 255, 255);")
        self.historyListButton.setObjectName("listButton")
        self.horizontalLayout.addWidget(self.historyListButton)

        self.resetSearch = QtWidgets.QPushButton(Form)
        self.resetSearch.setFont(font)
        # self.resetSearch.setStyleSheet("background-color: rgb(255, 0, 0);\n"
        #                                "color: rgb(255, 255, 255);")
        self.resetSearch.setObjectName("resetSearch")
        self.horizontalLayout.addWidget(self.resetSearch)

        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_left.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_left.addLayout(self.horizontalLayout_5)

        # 用于翻页设计

        self.horizontalLayout_paging = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_paging.setObjectName("horizontalLayout_paging")

        self.horizontalLayout_paging.setSpacing(0)
        self.horizontalLayout_paging.setAlignment(Qt.AlignRight)

        self.homePage = QtWidgets.QPushButton(Form)
        self.homePage.setObjectName("homePage")
        self.homePage.setFont(font)
        # self.homePage.setStyleSheet("font-size: 14px;")
        self.homePage.setMaximumSize(QtCore.QSize(60, 45))
        self.horizontalLayout_paging.addWidget(self.homePage)

        self.prePage = QtWidgets.QPushButton(Form)
        self.prePage.setObjectName("prePage")
        self.prePage.setFont(font)
        self.prePage.setMaximumSize(QtCore.QSize(100, 45))
        # self.prePage.setStyleSheet("font-size: 14px;")
        self.horizontalLayout_paging.addWidget(self.prePage)

        self.curPage = QLineEdit(Form)
        self.curPage.setObjectName("curPage")
        self.curPage.setFont(font)
        self.curPage.setMaximumSize(QtCore.QSize(100, 45))
        self.curPage.setReadOnly(True)
        self.curPage.setAlignment(Qt.AlignCenter)
        self.horizontalLayout_paging.addWidget(self.curPage)

        self.nextPage = QtWidgets.QPushButton(Form)
        self.nextPage.setObjectName("nextPage")
        self.nextPage.setFont(font)
        self.nextPage.setMaximumSize(QtCore.QSize(100, 45))
        # self.nextPage.setStyleSheet("font-size: 14px;")
        self.horizontalLayout_paging.addWidget(self.nextPage)

        self.finalPage = QtWidgets.QPushButton(Form)
        self.finalPage.setObjectName("finalPage")
        self.finalPage.setFont(font)
        self.finalPage.setMaximumSize(QtCore.QSize(60, 45))
        # self.finalPage.setStyleSheet("font-size: 14px;")
        self.horizontalLayout_paging.addWidget(self.finalPage)

        self.totalPage = QLabel(Form)
        self.totalPage.setObjectName("totalPage")
        self.totalPage.setFont(font)
        self.totalPage.setMaximumSize(QtCore.QSize(100, 26))
        self.horizontalLayout_paging.addWidget(self.totalPage)

        self.skipLable_0 = QLabel(Form)
        self.skipLable_0.setObjectName("totalPage")
        self.skipLable_0.setFont(font)
        self.skipLable_0.setMaximumSize(QtCore.QSize(100, 26))
        self.horizontalLayout_paging.addWidget(self.skipLable_0)

        self.skipPage = QLineEdit(Form)
        self.skipPage.setObjectName("skipPage")
        self.skipPage.setFont(font)
        self.skipPage.setMaximumSize(QtCore.QSize(56, 32))
        self.skipPage.setAlignment(Qt.AlignCenter)
        self.horizontalLayout_paging.addWidget(self.skipPage)

        self.skipLabel_1 = QLabel(Form)
        self.skipLabel_1.setObjectName("skipLabel_1")
        self.skipLabel_1.setFont(font)
        self.skipLabel_1.setMaximumSize(QtCore.QSize(30, 26))
        self.horizontalLayout_paging.addWidget(self.skipLabel_1)

        self.confirmSkip = QtWidgets.QPushButton(Form)
        self.confirmSkip.setObjectName("confirmSkip")
        self.confirmSkip.setFont(font)
        self.confirmSkip.setMaximumSize(QtCore.QSize(60, 45))
        self.horizontalLayout_paging.addWidget(self.confirmSkip)
        # self.confirmSkip.setStyleSheet("font-size: 14px;")
        self.horizontalLayout_5.addLayout(self.horizontalLayout_paging)

        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)

        self.selectButton = QtWidgets.QPushButton(Form)
        self.selectButton.setFont(font)
        self.selectButton.setMaximumSize(QtCore.QSize(180, 45))
        # self.selectButton.setStyleSheet("font-size: 14px;")
        # self.selectButton.setStyleSheet("background-color: rgb(255, 0, 0);\n"
        #                                 "color: rgb(255, 255, 255);")
        # self.selectButton.setObjectName("selectButton")
        self.horizontalLayout_5.addWidget(self.selectButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout_left)
        self.verticalLayout_right = QtWidgets.QVBoxLayout()
        self.verticalLayout_right.setContentsMargins(10, 45, 10, 10)
        self.verticalLayout_right.setObjectName("verticalLayout_right")
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPixelSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_right.addWidget(self.label_2)

        self.label5 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPixelSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label5.setFont(font)
        self.label5.setObjectName("label5")
        self.verticalLayout_right.addWidget(self.label5)

        self.tableWidget2 = QtWidgets.QTableWidget()
        self.tableWidget2.setObjectName("tableWidget")
        self.tableWidget2.setColumnCount(0)
        self.tableWidget2.setRowCount(0)
        self.verticalLayout_right.addWidget(self.tableWidget2)

        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPixelSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_right.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_right.addWidget(self.textEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.docSelBtn = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPixelSize(16)
        self.docSelBtn.setFont(font)
        self.docSelBtn.setMaximumSize(QtCore.QSize(120, 45))
        self.docSelBtn.setObjectName("docSelBtn")
        self.horizontalLayout_2.addWidget(self.docSelBtn)

        self.delButton = QtWidgets.QPushButton(Form)

        self.delButton.setFont(font)
        self.delButton.setMaximumSize(QtCore.QSize(120, 45))
        self.delButton.setObjectName("delButton")
        self.horizontalLayout_2.addWidget(self.delButton)
        self.verifyButton = QtWidgets.QPushButton(Form)
        self.verifyButton.setEnabled(True)

        # font.setBold(True)
        # font.setWeight(75)
        self.verifyButton.setFont(font)
        self.verifyButton.setMaximumSize(QtCore.QSize(120, 45))
        # self.verifyButton.setStyleSheet("font-size: 14px;")
        # self.verifyButton.setStyleSheet("background-color: rgb(255, 0, 0);\n"
        #                                 "color: rgb(255, 255, 255);")
        self.verifyButton.setObjectName("verifyButton")
        self.horizontalLayout_2.addWidget(self.verifyButton)
        self.verticalLayout_right.addLayout(self.horizontalLayout_2)
        self.verticalLayout_right.setStretch(0, 5)
        self.verticalLayout_right.setStretch(2, 3)
        self.verticalLayout_right.setStretch(4, 3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_right)
        self.horizontalLayout_3.setStretch(0, 3)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_all.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):

        dt = QtCore.QDateTime.currentDateTime().addDays(1)
        self.date_lineEdit.setDateTime(dt)
        self.date_lineEdit2.setDateTime(dt)

        self.lineEditDate2.setText("")
        self.lineEditDate1.setText("")

        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.docSelBtn.setText(_translate("Form", "选择医生"))
        self.delButton.setText(_translate("Form", "重置会诊"))
        self.historyListButton.setText(_translate("Form", "查询"))
        self.selectButton.setText(_translate("Form", "会诊数据选择"))
        self.label_2.setText(_translate("Form", "请选择会诊数据"))
        self.label.setText(_translate("Form", "发送信息内容"))
        self.label5.setText(_translate("Form", "新邀请医生名单"))
        self.verifyButton.setText(_translate("Form", "创建会诊"))


        self.label3.setText(_translate("Form", "关键字："))
        self.comboBox.setItemText(0, _translate("Form", "检查单号"))
        self.comboBox.setItemText(1, _translate("Form", "病人名称"))
        self.label2.setText(_translate("Form", "测量日期≥"))
        self.label4.setText(_translate("Form", "测量日期≤"))
        self.resetSearch.setText(_translate("Form", "重置搜索"))

        self.homePage.setText(_translate("Form", "首页"))
        self.prePage.setText(_translate("Form", "上一页"))
        self.curPage.setText(_translate("Form", "1"))
        self.nextPage.setText(_translate("Form", "下一页"))
        self.finalPage.setText(_translate("Form", "末页"))
        self.totalPage.setText(_translate("Form", "共1页"))
        self.skipLable_0.setText(_translate("Form", "  跳到第:"))
        self.skipPage.setText(_translate("Form", "1"))
        self.skipLabel_1.setText(_translate("Form", "页"))
        self.confirmSkip.setText(_translate("Form", "确定"))

    def dateChanged(self,gData):
        if gData==2:
            mdate =  self.date_lineEdit2.date().toString('yyyy-MM-dd')
            self.lineEditDate2.setText(mdate)
        else:
            mdate = self.date_lineEdit.date().toString('yyyy-MM-dd')
            self.lineEditDate1.setText(mdate)