# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prentry.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QHBoxLayout, QPushButton, QLabel, QLineEdit
from PyQt5.QtCore import QRect, Qt


class Ui_Prentry(object):
    def setupUi(self, Prentry):
        Prentry.setObjectName("Prentry")
        Prentry.resize(400, 600)
        self.gridLayout_2 = QtWidgets.QGridLayout(Prentry)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")

        self.horizontalLayout_top = QtWidgets.QHBoxLayout()
        self.horizontalLayout_top.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Prentry)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_top.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(Prentry)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_top.addWidget(self.comboBox)
        self.lineEdit = QtWidgets.QLineEdit(Prentry)
        self.lineEdit.setMaximumSize(QtCore.QSize(300, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_top.addWidget(self.lineEdit)
        font2 = QtGui.QFont()
        font2.setPointSize(14)
        self.searchDoc = QtWidgets.QPushButton(Prentry)
        self.searchDoc.setFont(font2)
        self.searchDoc.setObjectName("searchDoc")
        self.horizontalLayout_top.addWidget(self.searchDoc)

        self.resetSearch = QtWidgets.QPushButton(Prentry)
        self.resetSearch.setObjectName("resetSearch")
        self.resetSearch.setFont(font2)
        self.horizontalLayout_top.addWidget(self.resetSearch)

        self.gridLayout_2.addLayout(self.horizontalLayout_top, 0, 0, 1, 1)

        self.tableWidget = QtWidgets.QTableWidget(Prentry)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)

        # 用于翻页设计
        font2 = QtGui.QFont()
        font2.setPointSize(14)
        self.horizontalLayout_paging = QtWidgets.QHBoxLayout(Prentry)
        self.horizontalLayout_paging.setObjectName("horizontalLayout_paging")

        self.horizontalLayout_paging.setSpacing(0)
        self.horizontalLayout_paging.setAlignment(Qt.AlignRight)

        self.homePage = QtWidgets.QPushButton(Prentry)
        self.homePage.setObjectName("homePage")
        self.homePage.setFont(font2)

        self.homePage.setMaximumSize(QtCore.QSize(48, 26))
        self.horizontalLayout_paging.addWidget(self.homePage)

        self.prePage = QtWidgets.QPushButton(Prentry)
        self.prePage.setObjectName("prePage")
        self.prePage.setFont(font2)
        self.prePage.setMaximumSize(QtCore.QSize(80, 26))
        self.horizontalLayout_paging.addWidget(self.prePage)

        self.curPage = QLineEdit(Prentry)
        self.curPage.setObjectName("curPage")
        self.curPage.setFont(font2)
        self.curPage.setMaximumSize(QtCore.QSize(100, 26))
        self.curPage.setReadOnly(True)
        self.curPage.setAlignment(Qt.AlignCenter)
        self.horizontalLayout_paging.addWidget(self.curPage)

        self.nextPage = QtWidgets.QPushButton(Prentry)
        self.nextPage.setObjectName("nextPage")
        self.nextPage.setFont(font2)
        self.nextPage.setMaximumSize(QtCore.QSize(80, 26))
        self.horizontalLayout_paging.addWidget(self.nextPage)

        self.finalPage = QtWidgets.QPushButton(Prentry)
        self.finalPage.setObjectName("finalPage")
        self.finalPage.setFont(font2)
        self.finalPage.setMaximumSize(QtCore.QSize(48, 26))
        self.horizontalLayout_paging.addWidget(self.finalPage)

        self.totalPage = QLabel(Prentry)
        self.totalPage.setObjectName("totalPage")
        self.totalPage.setFont(font2)
        self.totalPage.setMaximumSize(QtCore.QSize(100, 26))
        self.horizontalLayout_paging.addWidget(self.totalPage)

        self.skipLable_0 = QLabel(Prentry)
        self.skipLable_0.setObjectName("totalPage")
        self.skipLable_0.setFont(font2)
        self.skipLable_0.setMaximumSize(QtCore.QSize(80, 26))
        self.horizontalLayout_paging.addWidget(self.skipLable_0)

        self.skipPage = QLineEdit(Prentry)
        self.skipPage.setObjectName("skipPage")
        self.skipPage.setFont(font2)
        self.skipPage.setMaximumSize(QtCore.QSize(48, 26))
        self.skipPage.setAlignment(Qt.AlignCenter)
        self.horizontalLayout_paging.addWidget(self.skipPage)

        self.skipLabel_1 = QLabel(Prentry)
        self.skipLabel_1.setObjectName("skipLabel_1")
        self.skipLabel_1.setFont(font2)
        self.skipLabel_1.setMaximumSize(QtCore.QSize(20, 26))
        self.horizontalLayout_paging.addWidget(self.skipLabel_1)

        self.confirmSkip = QtWidgets.QPushButton(Prentry)
        self.confirmSkip.setObjectName("confirmSkip")
        self.confirmSkip.setFont(font2)
        self.confirmSkip.setMaximumSize(QtCore.QSize(48, 26))
        self.horizontalLayout_paging.addWidget(self.confirmSkip)
        self.gridLayout_2.addLayout(self.horizontalLayout_paging, 2, 0, 1, 1)


        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnConfirm = QtWidgets.QPushButton(Prentry)
        self.btnConfirm.setFont(font2)
        self.btnConfirm.setObjectName("btnConfirm")
        self.horizontalLayout.addWidget(self.btnConfirm)
        self.btnReturn = QtWidgets.QPushButton(Prentry)
        self.btnReturn.setObjectName("btnReturn")
        self.horizontalLayout.addWidget(self.btnReturn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 0, 1, 1)

        self.retranslateUi(Prentry)
        QtCore.QMetaObject.connectSlotsByName(Prentry)

    def retranslateUi(self, Prentry):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("Form", "关键字："))
        self.comboBox.setItemText(0, _translate("Form", "医生账号"))
        self.comboBox.setItemText(1, _translate("Form", "会诊医生"))
        Prentry.setWindowTitle(_translate("Prentry", "Form"))
        self.btnConfirm.setText(_translate("Prentry", "确认选择"))
        self.searchDoc.setText(_translate("Prentry", "搜索"))
        self.resetSearch.setText(_translate("Form", "重置搜索"))
        self.btnReturn.setText(_translate("Prentry", "返回"))
        self.btnReturn.setVisible(False)

        self.homePage.setText(_translate("Form", "首页"))
        self.prePage.setText(_translate("Form", "<上一页"))
        self.curPage.setText(_translate("Form", "1"))
        self.nextPage.setText(_translate("Form", "下一页>"))
        self.finalPage.setText(_translate("Form", "末页"))
        self.totalPage.setText(_translate("Form", "共1页"))
        self.skipLable_0.setText(_translate("Form", "  跳到第:"))
        self.skipPage.setText(_translate("Form", "1"))
        self.skipLabel_1.setText(_translate("Form", "页"))
        self.confirmSkip.setText(_translate("Form", "跳转"))
